

<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>TI Calculation &mdash; PyGromosTools  documentation</title>



  <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />










  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->


      <script type="text/javascript" id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/doctools.js"></script>
        <script crossorigin="anonymous" integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>

    <script type="text/javascript" src="../_static/js/theme.js"></script>


    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="PyGromos File Examples" href="example_gromos_files.html" />
    <link rel="prev" title="Demonstartion of the PyGromosTools implementation of the Gromos++ programs" href="example_PyGromosPP.html" />
</head>

<body class="wy-body-for-nav">


  <div class="wy-grid-for-nav">

    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >



            <a href="../index.html" class="icon icon-home"> PyGromosTools



          </a>







<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>


        </div>


        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">






              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../introduction.html">Welcome to PyGromosTools</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="index.html">Examples</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="example_PyGromosPP.html">Demonstartion of the PyGromosTools implementation of the Gromos++ programs</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">TI Calculation</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#Imports">Imports</a></li>
<li class="toctree-l3"><a class="reference internal" href="#Input-files">Input files</a></li>
<li class="toctree-l3"><a class="reference internal" href="#Vacuum-Simulation">Vacuum Simulation</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#Direction-A-&gt;B">Direction A-&gt;B</a></li>
<li class="toctree-l4"><a class="reference internal" href="#RUN-Emin">RUN Emin</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#RUN-Test-SD-EQ">RUN Test SD EQ</a></li>
<li class="toctree-l3"><a class="reference internal" href="#Further-Analysis:">Further Analysis:</a></li>
<li class="toctree-l3"><a class="reference internal" href="#Lambda-Sampling">Lambda Sampling</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#Setup-again">Setup again</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#Submission">Submission</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="example_gromos_files.html">PyGromos File Examples</a></li>
<li class="toctree-l2"><a class="reference internal" href="example_gromos_simulation.html">SD Simulations with Submission System</a></li>
<li class="toctree-l2"><a class="reference internal" href="example_gromos_trajectories.html">Gromos Trajectory evaluation with Pygromos and Pandas</a></li>
<li class="toctree-l2"><a class="reference internal" href="example_submission_systems.html">Submission Systems</a></li>
<li class="toctree-l2"><a class="reference internal" href="example_topology_creation.html">Topology creation and modifications with PyGromosTools</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../Tutorials/index.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../_source/modules.html">Documentation</a></li>
</ul>



        </div>

      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">


      <nav class="wy-nav-top" aria-label="top navigation">

          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">PyGromosTools</a>

      </nav>


      <div class="wy-nav-content">

        <div class="rst-content">



















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">

      <li><a href="../index.html" class="icon icon-home"></a> &raquo;</li>

          <li><a href="index.html">Examples</a> &raquo;</li>

      <li>TI Calculation</li>


      <li class="wy-breadcrumbs-aside">


            <a href="../_sources/Examples/example_TI_gromos_simulation.ipynb.txt" rel="nofollow"> View page source</a>


      </li>

  </ul>


  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">


<style>
/* CSS for nbsphinx extension */

/* remove conflicting styling from Sphinx themes */
div.nbinput.container div.prompt *,
div.nboutput.container div.prompt *,
div.nbinput.container div.input_area pre,
div.nboutput.container div.output_area pre,
div.nbinput.container div.input_area .highlight,
div.nboutput.container div.output_area .highlight {
    border: none;
    padding: 0;
    margin: 0;
    box-shadow: none;
}

div.nbinput.container > div[class*=highlight],
div.nboutput.container > div[class*=highlight] {
    margin: 0;
}

div.nbinput.container div.prompt *,
div.nboutput.container div.prompt * {
    background: none;
}

div.nboutput.container div.output_area .highlight,
div.nboutput.container div.output_area pre {
    background: unset;
}

div.nboutput.container div.output_area div.highlight {
    color: unset;  /* override Pygments text color */
}

/* avoid gaps between output lines */
div.nboutput.container div[class*=highlight] pre {
    line-height: normal;
}

/* input/output containers */
div.nbinput.container,
div.nboutput.container {
    display: -webkit-flex;
    display: flex;
    align-items: flex-start;
    margin: 0;
    width: 100%;
}
@media (max-width: 540px) {
    div.nbinput.container,
    div.nboutput.container {
        flex-direction: column;
    }
}

/* input container */
div.nbinput.container {
    padding-top: 5px;
}

/* last container */
div.nblast.container {
    padding-bottom: 5px;
}

/* input prompt */
div.nbinput.container div.prompt pre {
    color: #307FC1;
}

/* output prompt */
div.nboutput.container div.prompt pre {
    color: #BF5B3D;
}

/* all prompts */
div.nbinput.container div.prompt,
div.nboutput.container div.prompt {
    width: 4.5ex;
    padding-top: 5px;
    position: relative;
    user-select: none;
}

div.nbinput.container div.prompt > div,
div.nboutput.container div.prompt > div {
    position: absolute;
    right: 0;
    margin-right: 0.3ex;
}

@media (max-width: 540px) {
    div.nbinput.container div.prompt,
    div.nboutput.container div.prompt {
        width: unset;
        text-align: left;
        padding: 0.4em;
    }
    div.nboutput.container div.prompt.empty {
        padding: 0;
    }

    div.nbinput.container div.prompt > div,
    div.nboutput.container div.prompt > div {
        position: unset;
    }
}

/* disable scrollbars on prompts */
div.nbinput.container div.prompt pre,
div.nboutput.container div.prompt pre {
    overflow: hidden;
}

/* input/output area */
div.nbinput.container div.input_area,
div.nboutput.container div.output_area {
    -webkit-flex: 1;
    flex: 1;
    overflow: auto;
}
@media (max-width: 540px) {
    div.nbinput.container div.input_area,
    div.nboutput.container div.output_area {
        width: 100%;
    }
}

/* input area */
div.nbinput.container div.input_area {
    border: 1px solid #e0e0e0;
    border-radius: 2px;
    /*background: #f5f5f5;*/
}

/* override MathJax center alignment in output cells */
div.nboutput.container div[class*=MathJax] {
    text-align: left !important;
}

/* override sphinx.ext.imgmath center alignment in output cells */
div.nboutput.container div.math p {
    text-align: left;
}

/* standard error */
div.nboutput.container div.output_area.stderr {
    background: #fdd;
}

/* ANSI colors */
.ansi-black-fg { color: #3E424D; }
.ansi-black-bg { background-color: #3E424D; }
.ansi-black-intense-fg { color: #282C36; }
.ansi-black-intense-bg { background-color: #282C36; }
.ansi-red-fg { color: #E75C58; }
.ansi-red-bg { background-color: #E75C58; }
.ansi-red-intense-fg { color: #B22B31; }
.ansi-red-intense-bg { background-color: #B22B31; }
.ansi-green-fg { color: #00A250; }
.ansi-green-bg { background-color: #00A250; }
.ansi-green-intense-fg { color: #007427; }
.ansi-green-intense-bg { background-color: #007427; }
.ansi-yellow-fg { color: #DDB62B; }
.ansi-yellow-bg { background-color: #DDB62B; }
.ansi-yellow-intense-fg { color: #B27D12; }
.ansi-yellow-intense-bg { background-color: #B27D12; }
.ansi-blue-fg { color: #208FFB; }
.ansi-blue-bg { background-color: #208FFB; }
.ansi-blue-intense-fg { color: #0065CA; }
.ansi-blue-intense-bg { background-color: #0065CA; }
.ansi-magenta-fg { color: #D160C4; }
.ansi-magenta-bg { background-color: #D160C4; }
.ansi-magenta-intense-fg { color: #A03196; }
.ansi-magenta-intense-bg { background-color: #A03196; }
.ansi-cyan-fg { color: #60C6C8; }
.ansi-cyan-bg { background-color: #60C6C8; }
.ansi-cyan-intense-fg { color: #258F8F; }
.ansi-cyan-intense-bg { background-color: #258F8F; }
.ansi-white-fg { color: #C5C1B4; }
.ansi-white-bg { background-color: #C5C1B4; }
.ansi-white-intense-fg { color: #A1A6B2; }
.ansi-white-intense-bg { background-color: #A1A6B2; }

.ansi-default-inverse-fg { color: #FFFFFF; }
.ansi-default-inverse-bg { background-color: #000000; }

.ansi-bold { font-weight: bold; }
.ansi-underline { text-decoration: underline; }


div.nbinput.container div.input_area div[class*=highlight] > pre,
div.nboutput.container div.output_area div[class*=highlight] > pre,
div.nboutput.container div.output_area div[class*=highlight].math,
div.nboutput.container div.output_area.rendered_html,
div.nboutput.container div.output_area > div.output_javascript,
div.nboutput.container div.output_area:not(.rendered_html) > img{
    padding: 5px;
    margin: 0;
}

/* fix copybtn overflow problem in chromium (needed for 'sphinx_copybutton') */
div.nbinput.container div.input_area > div[class^='highlight'],
div.nboutput.container div.output_area > div[class^='highlight']{
    overflow-y: hidden;
}

/* hide copybtn icon on prompts (needed for 'sphinx_copybutton') */
.prompt a.copybtn {
    display: none;
}

/* Some additional styling taken form the Jupyter notebook CSS */
div.rendered_html table {
  border: none;
  border-collapse: collapse;
  border-spacing: 0;
  color: black;
  font-size: 12px;
  table-layout: fixed;
}
div.rendered_html thead {
  border-bottom: 1px solid black;
  vertical-align: bottom;
}
div.rendered_html tr,
div.rendered_html th,
div.rendered_html td {
  text-align: right;
  vertical-align: middle;
  padding: 0.5em 0.5em;
  line-height: normal;
  white-space: normal;
  max-width: none;
  border: none;
}
div.rendered_html th {
  font-weight: bold;
}
div.rendered_html tbody tr:nth-child(odd) {
  background: #f5f5f5;
}
div.rendered_html tbody tr:hover {
  background: rgba(66, 165, 245, 0.2);
}

/* CSS overrides for sphinx_rtd_theme */

/* 24px margin */
.nbinput.nblast.container,
.nboutput.nblast.container {
    margin-bottom: 19px;  /* padding has already 5px */
}

/* ... except between code cells! */
.nblast.container + .nbinput.container {
    margin-top: -19px;
}

.admonition > p:before {
    margin-right: 4px;  /* make room for the exclamation icon */
}

/* Fix math alignment, see https://github.com/rtfd/sphinx_rtd_theme/pull/686 */
.math {
    text-align: unset;
}
</style>
<div class="section" id="TI-Calculation">
<h1>TI Calculation<a class="headerlink" href="#TI-Calculation" title="Permalink to this headline">¶</a></h1>
<div class="section" id="Imports">
<h2>Imports<a class="headerlink" href="#Imports" title="Permalink to this headline">¶</a></h2>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[1]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1">#for analysis</span>
<span class="kn">from</span> <span class="nn">matplotlib</span> <span class="kn">import</span> <span class="n">pyplot</span> <span class="k">as</span> <span class="n">plt</span>
<span class="o">%</span><span class="k">matplotlib</span> inline

<span class="kn">import</span> <span class="nn">os</span>
<span class="kn">import</span> <span class="nn">numpy</span> <span class="k">as</span> <span class="nn">np</span>
<span class="kn">import</span> <span class="nn">pygromos</span>
<span class="kn">from</span> <span class="nn">pygromos.files.gromos_system</span> <span class="kn">import</span> <span class="n">Gromos_System</span>
<span class="kn">from</span> <span class="nn">pygromos.hpc_queuing.submission_systems.local</span> <span class="kn">import</span> <span class="n">LOCAL</span> <span class="k">as</span> <span class="n">subSystem</span>
<span class="kn">from</span> <span class="nn">pygromos.files.blocks.imd_blocks</span> <span class="kn">import</span> <span class="n">PERTURBATION</span><span class="p">,</span> <span class="n">WRITETRAJ</span>

<span class="kn">from</span> <span class="nn">pygromos.utils</span> <span class="kn">import</span> <span class="n">bash</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="Input-files">
<h2>Input files<a class="headerlink" href="#Input-files" title="Permalink to this headline">¶</a></h2>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[2]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="n">root_dir</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">abspath</span><span class="p">(</span><span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">dirname</span><span class="p">(</span><span class="n">pygromos</span><span class="o">.</span><span class="vm">__file__</span><span class="p">)</span><span class="o">+</span><span class="s2">&quot;/../examples/example_files/TI_Calculation&quot;</span><span class="p">)</span>
<span class="n">root_in_dir</span> <span class="o">=</span> <span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/TI_input&quot;</span>
<span class="n">cnf_path</span> <span class="o">=</span> <span class="n">root_in_dir</span><span class="o">+</span><span class="s2">&quot;/M030_6KET.cnf&quot;</span>
<span class="n">top_path</span> <span class="o">=</span> <span class="n">root_in_dir</span> <span class="o">+</span> <span class="s2">&quot;/M030_6KET.top&quot;</span>
<span class="n">disres_path</span> <span class="o">=</span> <span class="n">root_in_dir</span><span class="o">+</span><span class="s2">&quot;/M030_6KET.disres&quot;</span>


<span class="n">sys_name</span> <span class="o">=</span> <span class="s2">&quot;M030_to_6KET&quot;</span>
<span class="n">lam</span> <span class="o">=</span> <span class="mi">0</span>

<span class="n">project_dir</span> <span class="o">=</span> <span class="n">bash</span><span class="o">.</span><span class="n">make_folder</span><span class="p">(</span><span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/&quot;</span><span class="o">+</span><span class="n">sys_name</span><span class="p">)</span>
<span class="n">input_dir</span> <span class="o">=</span> <span class="n">bash</span><span class="o">.</span><span class="n">make_folder</span><span class="p">(</span><span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/input&quot;</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="Vacuum-Simulation">
<h2>Vacuum Simulation<a class="headerlink" href="#Vacuum-Simulation" title="Permalink to this headline">¶</a></h2>
<div class="section" id="Direction-A-&gt;B">
<h3>Direction A-&gt;B<a class="headerlink" href="#Direction-A->B" title="Permalink to this headline">¶</a></h3>
<div class="section" id="Setup:">
<h4>Setup:<a class="headerlink" href="#Setup:" title="Permalink to this headline">¶</a></h4>
<div class="section" id="Build-pertubation-file">
<h5>Build pertubation file<a class="headerlink" href="#Build-pertubation-file" title="Permalink to this headline">¶</a></h5>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[3]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.files.topology.ptp</span> <span class="kn">import</span> <span class="n">Pertubation_topology</span>
<span class="kn">from</span> <span class="nn">pygromos.files.blocks.topology_blocks</span> <span class="kn">import</span> <span class="n">pertubation_lam_state</span><span class="p">,</span> <span class="n">atom_lam_pertubation_state</span><span class="p">,</span> <span class="n">PERTATOMPARAM</span><span class="p">,</span> <span class="n">TITLE</span>


<span class="c1">#External imd_changes:</span>
<span class="n">grom_system</span> <span class="o">=</span> <span class="n">Gromos_System</span><span class="p">(</span><span class="n">in_cnf_path</span><span class="o">=</span><span class="n">cnf_path</span><span class="p">,</span> <span class="n">in_top_path</span><span class="o">=</span><span class="n">top_path</span><span class="p">,</span>
                            <span class="n">in_disres_path</span><span class="o">=</span><span class="n">disres_path</span><span class="p">,</span>
                            <span class="n">system_name</span><span class="o">=</span><span class="n">sys_name</span><span class="p">,</span> <span class="n">work_folder</span><span class="o">=</span><span class="n">input_dir</span><span class="p">)</span>


<span class="c1">#Build up lambda - States</span>
<span class="n">pert_atoms</span><span class="o">=</span><span class="p">[]</span>
<span class="k">for</span> <span class="n">atom_line</span> <span class="ow">in</span> <span class="n">grom_system</span><span class="o">.</span><span class="n">top</span><span class="o">.</span><span class="n">SOLUTEATOM</span><span class="p">:</span>
    <span class="n">states</span> <span class="o">=</span> <span class="p">{}</span>
    <span class="n">phys_state</span> <span class="o">=</span> <span class="n">pertubation_lam_state</span><span class="p">(</span><span class="n">IAC</span><span class="o">=</span><span class="n">atom_line</span><span class="o">.</span><span class="n">IAC</span><span class="p">,</span> <span class="n">MASS</span><span class="o">=</span><span class="n">atom_line</span><span class="o">.</span><span class="n">MASS</span><span class="p">,</span> <span class="n">CHARGE</span><span class="o">=</span><span class="n">atom_line</span><span class="o">.</span><span class="n">CG</span><span class="p">)</span>
    <span class="n">states</span> <span class="o">=</span> <span class="p">{</span><span class="n">atom_line</span><span class="o">.</span><span class="n">MRES</span><span class="p">:</span> <span class="n">phys_state</span> <span class="p">}</span>

    <span class="n">pert_atom</span> <span class="o">=</span> <span class="n">atom_lam_pertubation_state</span><span class="p">(</span><span class="n">atom_line</span><span class="o">.</span><span class="n">ATNM</span><span class="p">,</span><span class="n">RES</span><span class="o">=</span><span class="n">atom_line</span><span class="o">.</span><span class="n">MRES</span><span class="p">,</span><span class="n">NAME</span><span class="o">=</span><span class="n">atom_line</span><span class="o">.</span><span class="n">PANM</span><span class="p">,</span> <span class="n">STATES</span><span class="o">=</span><span class="n">states</span><span class="p">)</span>
    <span class="n">pert_atoms</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">pert_atom</span><span class="p">)</span>
<span class="n">pert_atom_block</span> <span class="o">=</span> <span class="n">PERTATOMPARAM</span><span class="p">(</span><span class="n">pert_atoms</span><span class="p">)</span>

<span class="c1"># Generate ptp file</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">ptp</span> <span class="o">=</span> <span class="n">Pertubation_topology</span><span class="p">(</span><span class="n">in_value</span> <span class="o">=</span> <span class="kc">None</span><span class="p">)</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">ptp</span><span class="o">.</span><span class="n">PERTATOMPARAM</span> <span class="o">=</span> <span class="n">pert_atom_block</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">ptp</span><span class="o">.</span><span class="n">TITLE</span> <span class="o">=</span> <span class="n">TITLE</span><span class="p">(</span><span class="s2">&quot;Automatic generated pertubation file. &quot;</span><span class="p">)</span>

<span class="n">grom_system</span><span class="o">.</span><span class="n">ptp</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>


==================
        CHECK dependencies

Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input
Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.top
Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.cnf
Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.disres
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.top
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.cnf
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/TI_input/M030_6KET.disres
All dependencies are correct!


Generate Empty:  imd
Parsing File:  top
Parsing File:  cnf
Parsing File:  disres
</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
/home/bschroed/Documents/code/PyGromosTools/pygromos/files/gromos_system/gromos_system.py:131: UserWarning: No data provided to gromos_system
manual work needed
  if verbose: warnings.warn(&#34;No data provided to gromos_system\nmanual work needed&#34;)
</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[3]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
TITLE
Automatic generated pertubation file.
         &gt;&gt;&gt; Generated with python lib function_libs utilities. (riniker group)
         &gt;&gt;&gt; line_seperator: &#39;\n&#39;       field_seperator: &#39;\t&#39;   comments_char: &#39;#&#39;
END
PERTATOMPARAM
# NJLA           NPTB =          2
         26
# state_identifiers
#        state1          state2
#    NR   RES  NAME  IAC1mass1   CHARGE1  IAC2mass2   CHARGE2    ALPHLJ     ALPHCRF
    1     1    C9    16 15.035    0.05200    22 15.035    0.00000    1.00000    1.00000
    2     1    C6    64 12.011    0.21300    22 12.011    0.00000    1.00000    1.00000
    3     1    C2    64 12.011   -0.43400    22 12.011    0.00000    1.00000    1.00000
    4     1    H2    20 1.008    0.16900    22 1.008    0.00000    1.00000    1.00000
    5     1    C4    64 12.011    0.21300    22 12.011    0.00000    1.00000    1.00000
    6     1    C7    16 15.035    0.05200    22 15.035    0.00000    1.00000    1.00000
    7     1    C1    64 12.011   -0.43400    22 12.011    0.00000    1.00000    1.00000
    8     1    H1    20 1.008    0.16900    22 1.008    0.00000    1.00000    1.00000
    9     1    C5    64 12.011    0.21300    22 12.011    0.00000    1.00000    1.00000
   10     1    C3    64 12.011   -0.43400    22 12.011    0.00000    1.00000    1.00000
   11     1    H3    20 1.008    0.16900    22 1.008    0.00000    1.00000    1.00000
   12     1    C8    16 15.035    0.05200    22 15.035    0.00000    1.00000    1.00000
   13     2    H8    22 1.008    0.00000    59 1.008    0.45800    1.00000    1.00000
   14     2    O1    22 15.9994    0.00000    68 15.9994   -0.62000    1.00000    1.00000
   15     2    C5    22 12.011    0.00000    64 12.011    0.48400    1.00000    1.00000
   16     2    C2    22 12.011    0.00000    64 12.011   -0.35300    1.00000    1.00000
   17     2    H2    22 1.008    0.00000    20 1.008    0.18400    1.00000    1.00000
   18     2    C1    22 12.011    0.00000    64 12.011   -0.10700    1.00000    1.00000
   19     2    H1    22 1.008    0.00000    20 1.008    0.15200    1.00000    1.00000
   20     2    C3    22 12.011    0.00000    64 12.011   -0.29800    1.00000    1.00000
   21     2    H3    22 1.008    0.00000    20 1.008    0.14200    1.00000    1.00000
   22     2    C6    22 12.011    0.00000    64 12.011    0.40300    1.00000    1.00000
   23     2    C4    22 12.011    0.00000    64 12.011   -0.53100    1.00000    1.00000
   24     2    H4    22 1.008    0.00000    20 1.008    0.19400    1.00000    1.00000
   25     2    O2    22 15.9994    0.00000     4 15.9994   -0.38700    1.00000    1.00000
   26     2    C7    22 15.035    0.00000    16 15.035    0.27900    1.00000    1.00000
END
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[4]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1">##Write out all generated files</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">rebase_files</span><span class="p">()</span>

<span class="c1">##save Input System</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">save</span><span class="p">(</span><span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/initial_startSys.obj&quot;</span><span class="p">)</span>
<span class="n">grom_system</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
File imd is empty , can not be written!
</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
/home/bschroed/Documents/code/PyGromosTools/pygromos/files/gromos_system/gromos_system.py:551: UserWarning: Did not change file path as its only promised None
  if(self.verbose or True): warnings.warn(&#34;Did not change file path as its only promised &#34; + str(file_obj.path))
/home/bschroed/Documents/code/PyGromosTools/pygromos/files/gromos_system/gromos_system.py:798: UserWarning: FOUND ALREADY A FILE! SKIPPING!
  warnings.warn(&#34;FOUND ALREADY A FILE! SKIPPING!&#34;)
</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[4]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>

GROMOS SYSTEM: M030_to_6KET
################################################################################
WORKDIR: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input
LAST CHECKPOINT: None

GromosXX_bin: None
GromosPP_bin: None
FILES:
        imd: None
        top: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input/M030_to_6KET.top
        cnf: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input/M030_to_6KET.cnf
        disres: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input/M030_to_6KET.disres
        ptp: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input/M030_to_6KET.ptp
FUTURE PROMISE: False
SYSTEM:
        Solute: [&#39;M030&#39;, &#39;6KET&#39;]  resID: [1, 2]  natoms: 26
        SOLVENT:        []  nmolecules: 0  natoms: 0


</pre></div></div>
</div>
</div>
</div>
</div>
<div class="section" id="RUN-Emin">
<h3>RUN Emin<a class="headerlink" href="#RUN-Emin" title="Permalink to this headline">¶</a></h3>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[5]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1"># PREPARE EMIN</span>
<span class="c1">## IMPORT</span>
<span class="kn">from</span> <span class="nn">pygromos.data.simulation_parameters_templates</span> <span class="kn">import</span> <span class="n">template_emin_vac</span>
<span class="kn">from</span> <span class="nn">pygromos.simulations.modules.preset_simulation_modules</span> <span class="kn">import</span> <span class="n">emin</span>

<span class="n">grom_system</span> <span class="o">=</span> <span class="n">Gromos_System</span><span class="o">.</span><span class="n">load</span><span class="p">(</span><span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/initial_startSys.obj&quot;</span><span class="p">)</span>
<span class="n">step_name</span>  <span class="o">=</span> <span class="s2">&quot;a_emin&quot;</span> <span class="c1">#also the dir_name, out prefix etc.</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span> <span class="o">=</span> <span class="n">template_emin_vac</span> <span class="c1">#read template imd</span>

<span class="c1">#Pertubation for molecules to sim params</span>
<span class="n">pert_block</span>  <span class="o">=</span>  <span class="n">PERTURBATION</span><span class="p">(</span><span class="n">NTG</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">NRDGL</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">RLAM</span><span class="o">=</span><span class="n">lam</span><span class="p">,</span> <span class="n">DLAMT</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
                            <span class="n">ALPHC</span><span class="o">=</span><span class="mf">0.5</span><span class="p">,</span> <span class="n">ALPHLJ</span><span class="o">=</span><span class="mf">0.5</span><span class="p">,</span> <span class="n">NLAM</span><span class="o">=</span><span class="mi">2</span><span class="p">,</span> <span class="n">NSCALE</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">add_block</span><span class="p">(</span><span class="n">block</span><span class="o">=</span><span class="n">pert_block</span><span class="p">)</span>

<span class="c1">#save checkpoint system</span>
<span class="n">step_dir</span> <span class="o">=</span> <span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/&quot;</span><span class="o">+</span><span class="n">step_name</span>

</pre></div>
</div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[6]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1">#EXECUTE EMIN</span>
<span class="n">emin_gromos_system</span><span class="p">,</span> <span class="n">jobID</span> <span class="o">=</span> <span class="n">emin</span><span class="p">(</span><span class="n">in_gromos_system</span><span class="o">=</span><span class="n">grom_system</span><span class="p">,</span> <span class="n">project_dir</span><span class="o">=</span><span class="n">project_dir</span><span class="p">,</span>
                          <span class="n">step_name</span><span class="o">=</span><span class="n">step_name</span><span class="p">,</span> <span class="n">submission_system</span><span class="o">=</span><span class="n">subSystem</span><span class="p">())</span>

<span class="n">emin_gromos_system</span><span class="o">.</span><span class="n">save</span><span class="p">(</span><span class="n">step_dir</span><span class="o">+</span><span class="s2">&quot;/emin_out.obj&quot;</span><span class="p">)</span>
<span class="n">emin_gromos_system</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>


==================
        CHECK dependencies

Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/input
All dependencies are correct!


Generate Empty:  imd
Generate Empty:  top
Generate Empty:  cnf
################################################################################

a_emin
################################################################################

Script:  /home/bschroed/Documents/code/PyGromosTools/pygromos/hpc_queuing/job_scheduling/schedulers/simulation_scheduler.py
################################################################################
Simulation PREPERATION
################################################################################



################################################################################
Simulation Setup:
################################################################################

steps_per_run:  3000
equis:  0
simulation runs:  1
[]
################################################################################

 submit Final AnaLysis part

/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/ana_out.log
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/job_analysis.py
ANA jobID: 0
</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[6]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>

GROMOS SYSTEM: a_emin
################################################################################
WORKDIR: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin
LAST CHECKPOINT: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/emin_out.obj

GromosXX_bin: None
GromosPP_bin: None
FILES:
        imd: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/a_emin.imd
        top: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/a_emin.top
        cnf: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/a_emin.cnf
        disres: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/a_emin.disres
        ptp: /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/a_emin.ptp
FUTURE PROMISE: True
SYSTEM:
        Solute: [&#39;M030&#39;, &#39;6KET&#39;]  resID: [1, 2]  natoms: 26
        SOLVENT:        []  nmolecules: 0  natoms: 0


</pre></div></div>
</div>
</div>
</div>
<div class="section" id="RUN-Test-SD-EQ">
<h2>RUN Test SD EQ<a class="headerlink" href="#RUN-Test-SD-EQ" title="Permalink to this headline">¶</a></h2>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[7]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.data.simulation_parameters_templates</span> <span class="kn">import</span> <span class="n">template_sd</span>
<span class="kn">from</span> <span class="nn">pygromos.simulations.modules.preset_simulation_modules</span> <span class="kn">import</span> <span class="n">sd</span>

<span class="n">grom_system</span> <span class="o">=</span> <span class="n">Gromos_System</span><span class="o">.</span><span class="n">load</span><span class="p">(</span><span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/M030_to_6KET/a_emin/emin_out.obj&quot;</span><span class="p">)</span>
<span class="n">step_name</span>  <span class="o">=</span> <span class="s2">&quot;b_vacuum_sd&quot;</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span> <span class="o">=</span> <span class="n">template_sd</span>

<span class="c1">#Pertubation</span>
<span class="n">pert_block</span>  <span class="o">=</span>  <span class="n">PERTURBATION</span><span class="p">(</span><span class="n">NTG</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">NRDGL</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">RLAM</span><span class="o">=</span><span class="n">lam</span><span class="p">,</span> <span class="n">DLAMT</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span>
                            <span class="n">ALPHC</span><span class="o">=</span><span class="mf">0.5</span><span class="p">,</span> <span class="n">ALPHLJ</span><span class="o">=</span><span class="mf">0.5</span><span class="p">,</span> <span class="n">NLAM</span><span class="o">=</span><span class="mi">2</span><span class="p">,</span> <span class="n">NSCALE</span><span class="o">=</span><span class="mi">0</span><span class="p">)</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">add_block</span><span class="p">(</span><span class="n">block</span><span class="o">=</span><span class="n">pert_block</span><span class="p">)</span>

<span class="c1">#write out trajs:</span>
<span class="n">write_traj</span> <span class="o">=</span> <span class="n">WRITETRAJ</span><span class="p">(</span><span class="n">NTWX</span><span class="o">=</span><span class="mi">100</span><span class="p">,</span> <span class="n">NTWE</span><span class="o">=</span><span class="mi">100</span><span class="p">)</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">add_block</span><span class="p">(</span><span class="n">block</span><span class="o">=</span><span class="n">write_traj</span><span class="p">)</span>
<span class="n">step_dir</span> <span class="o">=</span> <span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/&quot;</span><span class="o">+</span><span class="n">step_name</span>

<span class="c1">#further mods:</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">CONSTRAINT</span><span class="o">.</span><span class="n">NTC</span> <span class="o">=</span> <span class="mi">3</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">FORCE</span><span class="o">.</span><span class="n">BONDS</span> <span class="o">=</span> <span class="mi">0</span>

<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">COVALENTFORM</span><span class="o">.</span><span class="n">NTBAH</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">COVALENTFORM</span><span class="o">.</span><span class="n">NTBDN</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">COVALENTFORM</span><span class="o">.</span><span class="n">NTBBH</span> <span class="o">=</span> <span class="mi">0</span>

<span class="n">grom_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">STEP</span><span class="o">.</span><span class="n">NSTLIM</span> <span class="o">=</span> <span class="mi">30000</span>



</pre></div>
</div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="n">sd_gromos_system</span><span class="p">,</span> <span class="n">jobID</span>  <span class="o">=</span> <span class="n">sd</span><span class="p">(</span><span class="n">in_gromos_system</span><span class="o">=</span><span class="n">grom_system</span><span class="p">,</span> <span class="n">project_dir</span><span class="o">=</span><span class="n">project_dir</span><span class="p">,</span>
                              <span class="n">step_name</span><span class="o">=</span><span class="n">step_name</span><span class="p">,</span> <span class="n">submission_system</span><span class="o">=</span><span class="n">subSystem</span><span class="p">(),</span> <span class="n">in_imd_path</span><span class="o">=</span><span class="kc">None</span><span class="p">,</span>
                      <span class="n">equilibration_runs</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">simulation_runs</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
<span class="n">sd_gromos_system</span><span class="o">.</span><span class="n">save</span><span class="p">(</span><span class="n">step_dir</span><span class="o">+</span><span class="s2">&quot;/sd_out_system.obj&quot;</span><span class="p">)</span>
<span class="n">sd_gromos_system</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>


==================
        CHECK dependencies

Check /home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin
All dependencies are correct!


Generate Empty:  imd
Generate Empty:  top
Generate Empty:  cnf
################################################################################

b_vacuum_sd
################################################################################

Script:  /home/bschroed/Documents/code/PyGromosTools/pygromos/hpc_queuing/job_scheduling/schedulers/simulation_scheduler.py
################################################################################
Simulation PREPERATION
################################################################################



################################################################################
Simulation Setup:
################################################################################

steps_per_run:  30000
equis:  1
simulation runs:  1
[]
[]
################################################################################

 submit Final AnaLysis part

/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/b_vacuum_sd/ana_out.log
/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/b_vacuum_sd/job_analysis.py
ANA jobID: 0
</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-8-5bbdbc5d1c43&gt;&#34;, line 3, in &lt;module&gt;
    equilibration_runs=1, simulation_runs=1)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/preset_simulation_modules.py&#34;, line 43, in sd
    analysis_script=analysis_script)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/general_simulation_modules.py&#34;, line 140, in simulation
    in_gromos_system.trc = Trc(input_value=final_trc_file+&#34;.h5&#34;)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-8-5bbdbc5d1c43&gt;&#34;, line 3, in &lt;module&gt;
    equilibration_runs=1, simulation_runs=1)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/preset_simulation_modules.py&#34;, line 43, in sd
    analysis_script=analysis_script)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/general_simulation_modules.py&#34;, line 140, in simulation
    in_gromos_system.trc = Trc(input_value=final_trc_file+&#34;.h5&#34;)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-8-5bbdbc5d1c43&gt;&#34;, line 3, in &lt;module&gt;
    equilibration_runs=1, simulation_runs=1)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/preset_simulation_modules.py&#34;, line 43, in sd
    analysis_script=analysis_script)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/simulations/modules/general_simulation_modules.py&#34;, line 140, in simulation
    in_gromos_system.trc = Trc(input_value=final_trc_file+&#34;.h5&#34;)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
</div>
<div class="section" id="Further-Analysis:">
<h2>Further Analysis:<a class="headerlink" href="#Further-Analysis:" title="Permalink to this headline">¶</a></h2>
<p>Transform the trc into a pdb traj to check it out with pymol :!)</p>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[8]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1">#final analysis dir:</span>
<span class="kn">from</span> <span class="nn">pygromos.utils</span> <span class="kn">import</span> <span class="n">bash</span>

<span class="n">out_ana</span> <span class="o">=</span> <span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/c_ana&quot;</span>
<span class="k">if</span><span class="p">(</span><span class="ow">not</span> <span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">exists</span><span class="p">(</span><span class="n">out_ana</span><span class="p">)):</span>
    <span class="n">bash</span><span class="o">.</span><span class="n">make_folder</span><span class="p">(</span><span class="n">out_ana</span><span class="p">)</span>
</pre></div>
</div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[9]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="n">project_dir</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
ERROR! Session/line number was not unique in database. History logging moved to new session 1404
</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[9]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
&#39;/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET&#39;
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[10]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.files.coord</span> <span class="kn">import</span> <span class="n">Cnf</span>
<span class="n">in_path</span><span class="o">=</span><span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/a_emin/analysis/data/a_emin.cnf&quot;</span>
<span class="n">cnf_file</span> <span class="o">=</span> <span class="n">Cnf</span><span class="p">(</span><span class="n">in_path</span><span class="p">)</span>
<span class="n">cnf_file</span><span class="o">.</span><span class="n">write_pdb</span><span class="p">(</span><span class="n">in_path</span><span class="o">.</span><span class="n">replace</span><span class="p">(</span><span class="s2">&quot;cnf&quot;</span><span class="p">,</span> <span class="s2">&quot;pdb&quot;</span><span class="p">))</span>

</pre></div>
</div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[10]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
&#39;/home/bschroed/Documents/code/PyGromosTools/examples/example_files/TI_Calculation/M030_to_6KET/a_emin/analysis/data/a_emin.pdb&#39;
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[11]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="n">cnf_file</span><span class="o">.</span><span class="n">visualize</span><span class="p">()</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area rendered_html docutils container">
<div id="3dmolviewer_16220459057398627"  style="position: relative; width: 400px; height: 400px">
        <p id="3dmolwarning_16220459057398627" style="background-color:#ffcccc;color:black">You appear to be running in JupyterLab (or JavaScript failed to load for some other reason).  You need to install the 3dmol extension: <br>
        <tt>jupyter labextension install jupyterlab_3dmol</tt></p>
        </div>
<script>

var loadScriptAsync = function(uri){
  return new Promise((resolve, reject) => {
    var tag = document.createElement('script');
    tag.src = uri;
    tag.async = true;
    tag.onload = () => {
      resolve();
    };
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
});
};

if(typeof $3Dmolpromise === 'undefined') {
$3Dmolpromise = null;
  $3Dmolpromise = loadScriptAsync('https://3dmol.csb.pitt.edu/build/3Dmol.js');
}

var viewer_16220459057398627 = null;
var warn = document.getElementById("3dmolwarning_16220459057398627");
if(warn) {
    warn.parentNode.removeChild(warn);
}
$3Dmolpromise.then(function() {
viewer_16220459057398627 = $3Dmol.createViewer($("#3dmolviewer_16220459057398627"),{backgroundColor:"white"});
    viewer_16220459057398627.addModel("26\n# \tMD++# exported wit PyGromosTools\nC  \t-2.859959910    0.433631680    0.007559000\nC  \t-1.370531700    0.130355830    0.002212630\nC  \t-0.923656880   -1.185836140   -0.004914040\nH  \t-1.646042420   -2.002002080   -0.006662890\nC  \t 0.437023590   -1.469509160   -0.009828060\nC  \t 0.919016070   -2.911043990   -0.017613540\nC  \t 1.353575230   -0.424337520   -0.007565730\nH  \t 2.421751800   -0.641868350   -0.011400120\nC  \t 0.918854630    0.896016500   -0.000452770\nC  \t-0.444551110    1.167011580    0.004411390\nH  \t-0.790284960    2.200825000    0.009995020\nC  \t 1.926221850    2.034263110    0.001986470\nH  \t-2.872220440    1.385081560    0.010492500\nO  \t-2.712860860    0.426366590   -0.003060180\nC  \t-1.373879500    0.188795690   -0.021126830\nC  \t-0.949770990   -1.145251010    0.000434240\nH  \t-1.682864420   -1.951115970   -0.035001770\nC  \t 0.408725880   -1.437206570   -0.039670830\nH  \t 0.742163900   -2.475012740   -0.031852810\nC  \t 1.347562910   -0.400359690    0.020691670\nH  \t 2.412640200   -0.631422560   -0.001702290\nC  \t 0.922051110    0.933163460   -0.004915550\nC  \t-0.447056300    1.223299570    0.035128330\nH  \t-0.785316570    2.259467560    0.029136370\nO  \t 1.734472530    2.023045630    0.038120280\nC  \t 3.144898240    1.786903560    0.036019830\n");
    viewer_16220459057398627.setStyle({"model": -1},{"stick": {}});
    viewer_16220459057398627.zoomTo();
viewer_16220459057398627.render();
});
</script></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[11]:
</pre></div>
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
&lt;py3Dmol.view at 0x7f50af7028d0&gt;
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.files.trajectory.trc</span> <span class="kn">import</span> <span class="n">Trc</span>

<span class="n">in_path</span><span class="o">=</span><span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/b_vacuum_sd/analysis/data/b_vacuum_sd.trc.h5&quot;</span>

<span class="n">trc</span> <span class="o">=</span> <span class="n">Trc</span><span class="p">(</span><span class="n">input_value</span><span class="o">=</span><span class="n">in_path</span><span class="p">)</span>
<span class="n">trc</span><span class="o">.</span><span class="n">write_pdb</span><span class="p">(</span><span class="n">out_ana</span><span class="o">+</span><span class="s2">&quot;/sd_traj.pdb&quot;</span><span class="p">,</span> <span class="n">cnf_file</span><span class="o">=</span><span class="n">cnf_path</span><span class="p">)</span><span class="c1">#grom_system.cnf.path)</span>
<span class="n">trc</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-b3615fac4e85&gt;&#34;, line 5, in &lt;module&gt;
    trc = Trc(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-b3615fac4e85&gt;&#34;, line 5, in &lt;module&gt;
    trc = Trc(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-b3615fac4e85&gt;&#34;, line 5, in &lt;module&gt;
    trc = Trc(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/trc.py&#34;, line 30, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.files.trajectory.tre</span> <span class="kn">import</span> <span class="n">Tre</span>

<span class="n">in_path</span><span class="o">=</span><span class="n">project_dir</span><span class="o">+</span><span class="s2">&quot;/b_vacuum_sd/analysis/data/b_vacuum_sd.tre.h5&quot;</span>

<span class="n">tre</span> <span class="o">=</span> <span class="n">Tre</span><span class="p">(</span><span class="n">input_value</span><span class="o">=</span><span class="n">in_path</span><span class="p">)</span>
<span class="n">tre</span>


</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-38475b66d665&gt;&#34;, line 5, in &lt;module&gt;
    tre = Tre(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/tre.py&#34;, line 27, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
ERROR! Session/line number was not unique in database. History logging moved to new session 1405
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-38475b66d665&gt;&#34;, line 5, in &lt;module&gt;
    tre = Tre(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/tre.py&#34;, line 27, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: &#39;&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-38475b66d665&gt;&#34;, line 5, in &lt;module&gt;
    tre = Tre(input_value=in_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/tre.py&#34;, line 27, in __init__
    super().__init__(input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 48, in __init__
    self._read_from_file(input_path=input_value, auto_save=auto_save, stride=stride, skip=skip)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 136, in _read_from_file
    self._read_db_from_hf5(input_path=input_path)
  File &#34;/home/bschroed/Documents/code/PyGromosTools/pygromos/files/trajectory/_general_trajectory.py&#34;, line 144, in _read_db_from_hf5
    self.database = pandas.read_hdf(path_or_buf=input_path, key=input_path.split(&#34;.&#34;)[-1])
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 399, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/io/pytables.py&#34;, line 542, in __init__
    tables = import_optional_dependency(&#34;tables&#34;)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pandas/compat/_optional.py&#34;, line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/importlib/__init__.py&#34;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 1006, in _gcd_import
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 983, in _find_and_load
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 967, in _find_and_load_unlocked
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 677, in _load_unlocked
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 728, in exec_module
  File &#34;&lt;frozen importlib._bootstrap&gt;&#34;, line 219, in _call_with_frames_removed
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/__init__.py&#34;, line 73, in &lt;module&gt;
    from .tests import print_versions, test
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/__init__.py&#34;, line 21, in &lt;module&gt;
    from tables.tests.common import print_versions
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/tables/tests/common.py&#34;, line 25, in &lt;module&gt;
    from pkg_resources import resource_filename
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3267, in &lt;module&gt;
    @_call_aside
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3251, in _call_aside
    f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 573, in _build_master
    ws = cls()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 566, in __init__
    self.add_entry(entry)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 622, in add_entry
    for dist in find_distributions(entry, True):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/pkg_resources/__init__.py&#34;, line 1979, in find_distributions
    importer = get_importer(path_item)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/pkgutil.py&#34;, line 419, in get_importer
    importer = path_hook(path_item)
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 1447, in path_hook_for_FileFinder
  File &#34;&lt;frozen importlib._bootstrap_external&gt;&#34;, line 101, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="c1">#Plot Potential Energies</span>
<span class="n">V_tot</span> <span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">array</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="nb">map</span><span class="p">(</span><span class="k">lambda</span> <span class="n">x</span><span class="p">:</span> <span class="n">x</span><span class="p">[</span><span class="mi">2</span><span class="p">],</span> <span class="n">tre</span><span class="o">.</span><span class="n">database</span><span class="o">.</span><span class="n">totals</span><span class="p">)))</span>
<span class="n">step</span> <span class="o">=</span> <span class="nb">len</span><span class="p">(</span><span class="n">tre</span><span class="o">.</span><span class="n">database</span><span class="o">.</span><span class="n">TIMESTEP_time</span><span class="p">)</span><span class="o">//</span><span class="mi">10</span>

<span class="n">plt</span><span class="o">.</span><span class="n">plot</span><span class="p">(</span><span class="n">tre</span><span class="o">.</span><span class="n">database</span><span class="o">.</span><span class="n">TIMESTEP_time</span><span class="p">,</span> <span class="n">V_tot</span><span class="p">)</span>
<span class="n">plt</span><span class="o">.</span><span class="n">xticks</span><span class="p">(</span><span class="n">np</span><span class="o">.</span><span class="n">round</span><span class="p">(</span><span class="nb">list</span><span class="p">(</span><span class="n">tre</span><span class="o">.</span><span class="n">database</span><span class="o">.</span><span class="n">TIMESTEP_time</span><span class="p">[::</span><span class="n">step</span><span class="p">]),</span><span class="mi">2</span><span class="p">))</span>
<span class="n">plt</span><span class="o">.</span><span class="n">xlabel</span><span class="p">(</span><span class="s2">&quot;$t~[ps]$&quot;</span><span class="p">)</span>
<span class="n">plt</span><span class="o">.</span><span class="n">ylabel</span><span class="p">(</span><span class="s2">&quot;$V~[kJ]$&quot;</span><span class="p">)</span>
<span class="n">plt</span><span class="o">.</span><span class="n">title</span><span class="p">(</span><span class="s2">&quot;V total timeseries&quot;</span><span class="p">)</span>
<span class="n">plt</span><span class="o">.</span><span class="n">savefig</span><span class="p">(</span><span class="n">out_ana</span><span class="o">+</span><span class="s2">&quot;/potential_energy_timeseries.png&quot;</span><span class="p">)</span>


</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-a2854131c25f&gt;&#34;, line 2, in &lt;module&gt;
    V_tot = np.array(list(map(lambda x: x[2], tre.database.totals)))
NameError: name &#39;tre&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
ERROR! Session/line number was not unique in database. History logging moved to new session 1406
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-a2854131c25f&gt;&#34;, line 2, in &lt;module&gt;
    V_tot = np.array(list(map(lambda x: x[2], tre.database.totals)))
NameError: name &#39;tre&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-a2854131c25f&gt;&#34;, line 2, in &lt;module&gt;
    V_tot = np.array(list(map(lambda x: x[2], tre.database.totals)))
NameError: name &#39;tre&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
</div>
<div class="section" id="Lambda-Sampling">
<h2>Lambda Sampling<a class="headerlink" href="#Lambda-Sampling" title="Permalink to this headline">¶</a></h2>
<div class="section" id="Setup-again">
<h3>Setup again<a class="headerlink" href="#Setup-again" title="Permalink to this headline">¶</a></h3>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">import</span> <span class="nn">os</span>
<span class="kn">import</span> <span class="nn">numpy</span> <span class="k">as</span> <span class="nn">np</span>
<span class="kn">from</span> <span class="nn">pygromos.files.gromos_system</span> <span class="kn">import</span> <span class="n">Gromos_System</span>
<span class="kn">from</span> <span class="nn">pygromos.hpc_queuing.submission_systems.local</span> <span class="kn">import</span> <span class="n">LOCAL</span> <span class="k">as</span> <span class="n">subSystem</span>

<span class="kn">from</span> <span class="nn">pygromos.utils</span> <span class="kn">import</span> <span class="n">bash</span>
<span class="n">sys_name</span> <span class="o">=</span> <span class="s2">&quot;M030_to_6KET&quot;</span>
<span class="n">root_dir</span> <span class="o">=</span> <span class="n">os</span><span class="o">.</span><span class="n">getcwd</span><span class="p">()</span><span class="o">+</span><span class="s2">&quot;/example_files/TI_Calculation&quot;</span>

<span class="n">project_dir</span> <span class="o">=</span> <span class="n">bash</span><span class="o">.</span><span class="n">make_folder</span><span class="p">(</span><span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/&quot;</span><span class="o">+</span><span class="n">sys_name</span><span class="p">)</span>
<span class="n">sys_path</span> <span class="o">=</span> <span class="n">root_dir</span><span class="o">+</span><span class="s2">&quot;/M030_to_6KET/b_vacuum_sd/sd_out_system.obj&quot;</span>
<span class="n">sd_gromos_system</span> <span class="o">=</span> <span class="n">Gromos_System</span><span class="o">.</span><span class="n">load</span><span class="p">(</span><span class="n">sys_path</span><span class="p">)</span>

<span class="n">sd_gromos_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">WRITETRAJ</span><span class="o">.</span><span class="n">NTWG</span> <span class="o">=</span>  <span class="n">sd_gromos_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">WRITETRAJ</span><span class="o">.</span><span class="n">NTWX</span> <span class="o">=</span> <span class="n">sd_gromos_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">WRITETRAJ</span><span class="o">.</span><span class="n">NTWE</span> <span class="o">=</span><span class="mi">10</span>
<span class="n">sd_gromos_system</span><span class="o">.</span><span class="n">imd</span><span class="o">.</span><span class="n">STEP</span> <span class="o">=</span> <span class="mi">100</span>

<span class="n">sd_gromos_system</span>
</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-1e1b15c14c55&gt;&#34;, line 8, in &lt;module&gt;
    root_dir = os.getcwd()+&#34;/example_files/TI_Calculation&#34;
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
ERROR! Session/line number was not unique in database. History logging moved to new session 1407
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-1e1b15c14c55&gt;&#34;, line 8, in &lt;module&gt;
    root_dir = os.getcwd()+&#34;/example_files/TI_Calculation&#34;
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-1e1b15c14c55&gt;&#34;, line 8, in &lt;module&gt;
    root_dir = os.getcwd()+&#34;/example_files/TI_Calculation&#34;
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;FileNotFoundError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
</div>
</div>
<div class="section" id="Submission">
<h2>Submission<a class="headerlink" href="#Submission" title="Permalink to this headline">¶</a></h2>
<div class="nbinput docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span><span class="kn">from</span> <span class="nn">pygromos.simulations.modules.ti_modules</span> <span class="kn">import</span> <span class="n">TI_sampling</span>

<span class="n">step_name</span>  <span class="o">=</span> <span class="s2">&quot;d_lambda_sampling&quot;</span>


<span class="n">TI_sampling</span><span class="p">(</span><span class="n">in_gromos_system</span> <span class="o">=</span> <span class="n">sd_gromos_system</span><span class="p">,</span> <span class="n">project_dir</span><span class="o">=</span><span class="n">project_dir</span><span class="p">,</span> <span class="n">step_name</span>  <span class="o">=</span> <span class="n">step_name</span><span class="p">,</span>
            <span class="n">lambda_values</span><span class="o">=</span> <span class="n">np</span><span class="o">.</span><span class="n">arange</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mf">1.1</span><span class="p">,</span> <span class="mf">0.1</span><span class="p">),</span>
            <span class="n">subSystem</span><span class="o">=</span><span class="n">subSystem</span><span class="p">(),</span> <span class="n">n_simulation_repetitions</span> <span class="o">=</span> <span class="mi">3</span><span class="p">,</span> <span class="n">n_equilibrations</span> <span class="o">=</span> <span class="mi">1</span><span class="p">)</span>

</pre></div>
</div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-7457f4d28234&gt;&#34;, line 6, in &lt;module&gt;
    TI_sampling(in_gromos_system = sd_gromos_system, project_dir=project_dir, step_name  = step_name,
NameError: name &#39;sd_gromos_system&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
<div class="nboutput docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area stderr docutils container">
<div class="highlight"><pre>
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

</pre></div></div>
</div>
<div class="nboutput nblast docutils container">
<div class="prompt empty docutils container">
</div>
<div class="output_area docutils container">
<div class="highlight"><pre>
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-7457f4d28234&gt;&#34;, line 6, in &lt;module&gt;
    TI_sampling(in_gromos_system = sd_gromos_system, project_dir=project_dir, step_name  = step_name,
NameError: name &#39;sd_gromos_system&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
ERROR! Session/line number was not unique in database. History logging moved to new session 1408
Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File &#34;&lt;ipython-input-12-7457f4d28234&gt;&#34;, line 6, in &lt;module&gt;
    TI_sampling(in_gromos_system = sd_gromos_system, project_dir=project_dir, step_name  = step_name,
NameError: name &#39;sd_gromos_system&#39; is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;NameError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3347, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3444, in run_code
    self.showtraceback(running_compiled_code=True)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1125, in structured_traceback
    tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2932, in _run_cell
    return runner(coro)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/async_helpers.py&#34;, line 68, in _pseudo_sync_runner
    coro.send(None)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3156, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 3366, in run_ast_nodes
    self.showtraceback()
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2057, in showtraceback
    value, tb, tb_offset=tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1368, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1268, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1143, in structured_traceback
    chained_exceptions_tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1082, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 382, in find_recursion
    return len(records), 0
TypeError: object of type &#39;NoneType&#39; has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/interactiveshell.py&#34;, line 2054, in showtraceback
    stb = value._render_traceback_()
AttributeError: &#39;TypeError&#39; object has no attribute &#39;_render_traceback_&#39;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 248, in wrapped
    return f(*args, **kwargs)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/site-packages/IPython/core/ultratb.py&#34;, line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 696, in getsourcefile
    if getattr(getmodule(object, filename), &#39;__loader__&#39;, None) is not None:
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 725, in getmodule
    file = getabsfile(object, _filename)
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/inspect.py&#34;, line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File &#34;/home/bschroed/anaconda3/envs/pygromos/lib/python3.7/posixpath.py&#34;, line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
</pre></div></div>
</div>
<div class="nbinput nblast docutils container">
<div class="prompt highlight-none notranslate"><div class="highlight"><pre><span></span>[ ]:
</pre></div>
</div>
<div class="input_area highlight-ipython3 notranslate"><div class="highlight"><pre>
<span></span>
</pre></div>
</div>
</div>
</div>
</div>


           </div>

          </div>
          <footer>
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
        <a href="example_gromos_files.html" class="btn btn-neutral float-right" title="PyGromos File Examples" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
        <a href="example_PyGromosPP.html" class="btn btn-neutral float-left" title="Demonstartion of the PyGromosTools implementation of the Gromos++ programs" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>
        &#169; Copyright 2020, Benjamin Ries, Mark Lehner, Salome Rieder. Project structure based on the Computational Molecular Science Python Cookiecutter version 1.3.

    </p>
  </div>



    Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a

    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>

    provided by <a href="https://readthedocs.org">Read the Docs</a>.

</footer>
        </div>
      </div>

    </section>

  </div>


  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>






</body>
</html>
